version: '3.4'

services:
  database:
    image: ${DOCKER_REGISTRY}dev-database
    ports:
      - 2433:1433
  webapp:
    image: ${DOCKER_REGISTRY}webapp
    build:
      context: WebApp
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=WebApp;User Id=AppUser;Password=D3vP@ssw0rd
    depends_on:
      - database
